### PR TITLE
adding test cases to solidify testing for 4.3

### PR DESCRIPTION
**Pull request by raphobe**
Hey folks, when I was coding my solution to 4.3 in the book I found a couple edge cases when I was coding my own tests. It took a bit to get it right so I ended up pulling down y'alls repo to see if i could find more bugs in my solution and ended up adding two of my (imho) more important test cases to the repo. Let me know if y'all have any questions, will keep working through the book in my spare time

### CODE REVIEW

**Comment by raphobe** [comment]
Hey folks, so I think it turned out that the java test framework didn't actually allow for the correct initialization of legitimate 64 bit values that were larger than the max allowed for signed longs in java. I think I've developed a fix for this, but someone who is more familiar with the other bit manipulation questions in the book might want to verify that there are no other problems that need a similar fix.

Additionally, it also appears to me that at least the test cases that were in existence for reverse bits could probably be regenerated, because they appear to exclude all odd values and all values that are greater than max signed long value. Can someone comment on the above suspicions and verify?

**Comment by raphobe** [comment]
@metopa @tsunghsienlee @adnanaziz can someone comment on the above and merge in or provide guidance about what fixes they'd like to see, and what other problems that rely on unsigned properties should be examined (or if I'm way off base here)? (Also worth pointing out that it could be worthwhile for a CONTRIBUTING.md file to exist so we don't have to make this quite so ad hoc)

**Comment by metopa** [comment]
@raphobe Hi, I'm sorry for the delay. However, I'm fully loaded with work and school for now, so I won't be able to review this immediately. I'll get to this as soon as I'll be able.

**Comment by metopa** [comment]
@raphobe I'll check this out after my state exams in the end of June. I'll keep you updated :)

**Pull request closed without merging**
