### PR TITLE
In power_set.py solutions the output was the indices of the array instead of the elements of the array 

### PR DESCRIPTION
**Pull request by borundev**
The same is the case in the book as well

### CODE REVIEW

**Comment by tsunghsienlee** [comment]
Hi @borundev ,

This actually is a bug, and really appreciate for your report. This fix will be released in the next version.

**Comment by metopa** [comment]
@borundev Please, resolve merge conflicts against dev branch and I'll be happy to merge it!

**Comment by borundev** [comment]
@metopa The dev branch code is different and does not have the bug.

**Comment by metopa** [comment]
@borundev Well, it means it has been fixed already some time ago. Master branch is quite stale, we're going to release the next versions soon.

**Comment by borundev** [comment]
@metopa @tsunghsienlee 

Indeed the bug is fixed in dev but I think the fixing is incidental. What I mean is that the dev code is very different from the master code. 

However, one should ask why the master code was still passing the tests despite there being a bug. If you look at the power_set.tsv file of master, it has inputs where all the terms are integers 1 to n (eg [1,3,2] but never [1,4,2]). So the unordered match on indices is the same as that on the actual output.

Eyeballing the power_set.tsv in the dev version, it seems to have the same issue so it will be useful to add some non-trivial examples in power_set.tsv.

**Pull request closed without merging**
